### ISSUE TITLE
RotatedRect_.mexw64文件兼容的MATLAB版本

### ISSUE THREAD

**Issue by yiyihao2000** [roylin1229/line_segment_review#2]
您好！我认为您的工作非常出色，使线匹配邻域更完善，请问您在评估代码是在哪个matlab版本上编译的？
同时，我在运行中报错如下：
MEX 文件 'E:\1研究生\evalute\line_segment_review-main\eva_survey_p\RotatedRect_.mexw64' 无效: 找不到指定的模块。

出错 RotatedRect.points

出错 eva_unit

出错 eva_detection_wo_gt (第 17 行)
[mat_dist_1, mat_angle_1, mat_iou_1]  = eva_unit(ref_line_t, test_line, eval_param);

出错 eva_desc (第 41 行)
[index_pairs]                   = eva_detection_wo_gt(ref_lines_t, test_lines, eval_param);

出错 eva_description_demo (第 27 行)
[recall, precision, match_num, index_pairs_desc_v, index_pairs_desc, ref_lines, test_lines] = eva_desc(test_img, ref_img, test_kl, ref_kl, H, eval_param, 0);
希望你可以指导我走出迷津，
同时想问您的RotatedRect_.mexw64文件兼容哪个MATLAB版本（因为我怀疑可能和版本有关）
感激不尽！

**Comment by roylin1229** [comment]
> 您好！我认为您的工作非常出色，使线匹配邻域更完善，请问您在评估代码是在哪个matlab版本上编译的？ 同时，我在运行中报错如下： MEX 文件 'E:\1研究生\evalute\line_segment_review-main\eva_survey_p\RotatedRect_.mexw64' 无效: 找不到指定的模块。
> 
> 出错 RotatedRect.points
> 
> 出错 eva_unit
> 
> 出错 eva_detection_wo_gt (第 17 行) [mat_dist_1, mat_angle_1, mat_iou_1] = eva_unit(ref_line_t, test_line, eval_param);[mat_dist_1，mat_angle_1，mat_iou_1] = eva_unit（ref_line_t，test_line，eval_param）；
> 
> 出错 eva_desc (第 41 行) [index_pairs] = eva_detection_wo_gt(ref_lines_t, test_lines, eval_param);[index_pairs] = eva_detection_wo_gt（ref_lines_t，test_lines，eval_param）；
> 
> 出错 eva_description_demo (第 27 行) [recall, precision, match_num, index_pairs_desc_v, index_pairs_desc, ref_lines, test_lines] = eva_desc(test_img, ref_img, test_kl, ref_kl, H, eval_param, 0);[召回率、精确度、匹配数、索引对_desc_v、索引对_desc、参考线、测试线] = eva_desc（test_img、ref_img、test_kl、ref_kl、H、eval_param、0）； 希望你可以指导我走出迷津， 同时想问您的RotatedRect_.mexw64文件兼容哪个MATLAB版本（因为我怀疑可能和版本有关） 感激不尽！

你好，我用的学校正版MATLAB，如果你有编译问题，可以给我邮件地址，我邮件发你编译好的mex文件。(mailto:roylin_cv@163.com)

**Comment by roylin1229** [comment]
> 您好！我认为您的工作非常出色，使线匹配邻域更完善，请问您在评估代码是在哪个matlab版本上编译的？ 同时，我在运行中报错如下： MEX 文件 'E:\1研究生\evalute\line_segment_review-main\eva_survey_p\RotatedRect_.mexw64' 无效: 找不到指定的模块。
> 
> 出错 RotatedRect.points
> 
> 出错 eva_unit
> 
> 出错 eva_detection_wo_gt (第 17 行) [mat_dist_1, mat_angle_1, mat_iou_1] = eva_unit(ref_line_t, test_line, eval_param);[mat_dist_1，mat_angle_1，mat_iou_1] = eva_unit（ref_line_t，test_line，eval_param）；
> 
> 出错 eva_desc (第 41 行) [index_pairs] = eva_detection_wo_gt(ref_lines_t, test_lines, eval_param);[index_pairs] = eva_detection_wo_gt（ref_lines_t，test_lines，eval_param）；
> 
> 出错 eva_description_demo (第 27 行) [recall, precision, match_num, index_pairs_desc_v, index_pairs_desc, ref_lines, test_lines] = eva_desc(test_img, ref_img, test_kl, ref_kl, H, eval_param, 0);[召回率、精确度、匹配数、索引对_desc_v、索引对_desc、参考线、测试线] = eva_desc（test_img、ref_img、test_kl、ref_kl、H、eval_param、0）； 希望你可以指导我走出迷津， 同时想问您的RotatedRect_.mexw64文件兼容哪个MATLAB版本（因为我怀疑可能和版本有关） 感激不尽！

你好，我用的学校正版MATLAB，如果你有编译问题，可以给我邮件地址，我邮件发你编译好的mex文件。(mailto:roylin_cv@163.com)
